//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Address
    {
        public int Address_Id { get; set; }
        public int User_Id { get; set; }
        public Nullable<int> Address_Type_Id { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Town { get; set; }
        public string Zip_Code { get; set; }
        public string Street_Number { get; set; }
    
        public virtual Tbl_Address_Type Tbl_Address_Type { get; set; }
    }
}
