//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Contact
    {
        public int Contact_Id { get; set; }
        public int User_Id { get; set; }
        public string Contact { get; set; }
        public Nullable<int> Contact_Type_Id { get; set; }
    
        public virtual Tbl_Contact_Type Tbl_Contact_Type { get; set; }
    }
}
