//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        public int User_Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Role_Type_Id { get; set; }
        public Nullable<int> Status_Type_Id { get; set; }
        public Nullable<int> Reg_Mode_Type_Id { get; set; }
        public Nullable<int> Address_Type_Id { get; set; }
        public Nullable<int> File_Type_Id { get; set; }
        public Nullable<int> Contact_Type_Id { get; set; }
    
        public virtual Tbl_Address_Type Tbl_Address_Type { get; set; }
        public virtual Tbl_Contact_Type Tbl_Contact_Type { get; set; }
        public virtual Tbl_File_Type Tbl_File_Type { get; set; }
        public virtual Tbl_Reg_Mode Tbl_Reg_Mode { get; set; }
        public virtual Tbl_Role_Type Tbl_Role_Type { get; set; }
        public virtual Tbl_Status_Type Tbl_Status_Type { get; set; }
        public virtual Tbl_Reg_Mode_Type Tbl_Reg_Mode_Type { get; set; }
    }
}
