//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Role
    {
        public int Role_Id { get; set; }
        public int User_Id { get; set; }
        public Nullable<int> Role_Type_Id { get; set; }
    
        public virtual Tbl_Role_Type Tbl_Role_Type { get; set; }
    }
}
